/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radiosveglia2;

import javax.swing.Timer;

/**
 *
 * @author lleshi.alessandro
 */
public class SvegliaInterfaccia extends javax.swing.JFrame {

 Sveglia radioSveglia;
    Timer timer;

    public SvegliaInterfaccia() {
        initComponents();
        this.setSize(800, 700);

        radioSveglia = new Sveglia();
        timer = new Timer(60000, e -> {
            
            String[] array = radioSveglia.aumentaTempoSveglia();
            jLabel10.setText(array[0]);
            jLabel21.setText(array[1]);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ora = new javax.swing.JButton();
        sveglia = new javax.swing.JButton();
        data = new javax.swing.JButton();
        stazione = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        piu = new javax.swing.JButton();
        meno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("00:00");
        jScrollPane3.setViewportView(jTextArea3);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel12.setText("00:00");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel20.setText(":");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel22.setText("00");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel23.setText(":");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel24.setText("00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio Sveglia");
        setSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setText("Radio Sveglia");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(199, 42, 210, 80);

        ora.setText("imposta ora");
        ora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oraActionPerformed(evt);
            }
        });
        getContentPane().add(ora);
        ora.setBounds(18, 147, 210, 23);

        sveglia.setText("imposta sveglia");
        sveglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svegliaActionPerformed(evt);
            }
        });
        getContentPane().add(sveglia);
        sveglia.setBounds(18, 215, 210, 23);

        data.setText("imposta data");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        getContentPane().add(data);
        data.setBounds(18, 262, 171, 23);

        stazione.setText("cambia stazione");
        stazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stazioneActionPerformed(evt);
            }
        });
        getContentPane().add(stazione);
        stazione.setBounds(18, 321, 116, 23);

        jLabel2.setText("volume");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(73, 373, 40, 32);

        piu.setText("+");
        piu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AumentaVol(evt);
            }
        });
        piu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piuActionPerformed(evt);
            }
        });
        getContentPane().add(piu);
        piu.setBounds(124, 374, 43, 32);

        meno.setText("-");
        meno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiminuisciVOl(evt);
            }
        });
        meno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoActionPerformed(evt);
            }
        });
        getContentPane().add(meno);
        meno.setBounds(18, 374, 43, 32);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(265, 275, 10, 0);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RTL 102.5", "Subasio 107.7", "RDS 103.450", "Arctic Monkeys 105.67" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(158, 321, 152, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(272, 140, 55, 36);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(272, 210, 55, 36);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 265, 55, 36);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(272, 265, 55, 36);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(350, 265, 55, 36);

        jLabel5.setText("ora");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(441, 150, 30, 16);

        jLabel6.setText("ora sveglia");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(441, 218, 100, 16);

        jLabel7.setText("data");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(441, 275, 60, 16);

        jLabel8.setText("stazione");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 324, 80, 16);

        jLabel9.setText("volume");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(442, 381, 76, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel10.setText("00");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(581, 143, 34, 36);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel13.setText("gg");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 262, 33, 36);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel14.setText("mm");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(575, 262, 41, 36);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel15.setText("aa");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(634, 262, 45, 36);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel16.setText("0.00");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(461, 321, 162, 36);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jLabel17.setText("Hz");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(635, 321, 23, 36);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel18.setText("5");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(524, 370, 26, 36);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(621, 143, 13, 36);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel21.setText("00");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(640, 143, 31, 36);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel25.setText("00");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(575, 203, 34, 36);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel26.setText(":");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(615, 203, 13, 36);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel27.setText("00");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(634, 203, 31, 36);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(350, 140, 55, 36);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(350, 210, 55, 36);

        jLabel11.setText("ore");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 120, 26, 16);

        jLabel28.setText("min");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(350, 120, 26, 16);

        jLabel29.setText("min");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(350, 190, 23, 16);

        jLabel30.setText("ore");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(280, 190, 26, 16);

        jLabel31.setText("-");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(260, 275, 10, 16);

        jLabel32.setText("-");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(335, 275, 10, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void svegliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svegliaActionPerformed
        int ore = Integer.parseInt(jTextField2.getText());
        int min = Integer.parseInt(jTextField8.getText());
        radioSveglia.setOrarioSveglia(ore, min);

        jLabel25.setText(String.format("%02d", radioSveglia.getOrarioSveglia().getHour()));
        jLabel27.setText(String.format("%02d", radioSveglia.getOrarioSveglia().getMinute()));

    }//GEN-LAST:event_svegliaActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        int giorno = Integer.parseInt(jTextField3.getText());
        int mese = Integer.parseInt(jTextField4.getText());
        int anno = Integer.parseInt(jTextField6.getText());

        radioSveglia.setData(anno, mese, giorno);

        jLabel13.setText(String.format("%02d", radioSveglia.getData().getDayOfMonth()));
        jLabel14.setText(String.format("%02d", radioSveglia.getData().getMonthValue()));
        jLabel15.setText(String.valueOf(radioSveglia.getData().getYear()));
    }//GEN-LAST:event_dataActionPerformed

    private void stazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stazioneActionPerformed
        radioSveglia.setFrequenza((String) jComboBox1.getSelectedItem());
        jLabel16.setText(radioSveglia.getFrequenza());
    }//GEN-LAST:event_stazioneActionPerformed

    private void menoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoActionPerformed

    private void piuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piuActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        int ore = Integer.parseInt(jTextField2.getText());
        int min = Integer.parseInt(jTextField8.getText());
        
        radioSveglia.setOrario(ore, min);
        jLabel10.setText(String.valueOf(radioSveglia.getOrario()));
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void AumentaVol(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AumentaVol
        radioSveglia.aumentaVol();
        jLabel18.setText(String.valueOf(radioSveglia.getVolume()));
    }//GEN-LAST:event_AumentaVol

    private void DiminuisciVOl(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiminuisciVOl
        radioSveglia.diminuisciVol();
        jLabel18.setText(String.valueOf(radioSveglia.getVolume()));
    }//GEN-LAST:event_DiminuisciVOl

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        int ore = Integer.parseInt(jTextField1.getText());
        int min = Integer.parseInt(jTextField7.getText());
        radioSveglia.setOrario(ore, min);
        
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void oraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oraActionPerformed
        int ore = Integer.parseInt(jTextField1.getText());
        int min = Integer.parseInt(jTextField7.getText());
        radioSveglia.setOrario(ore, min);

        jLabel10.setText(String.format("%02d", radioSveglia.getOrario().getHour()));
        jLabel21.setText(String.format("%02d", radioSveglia.getOrario().getMinute())); 
        
        timer.stop();
        timer.start();
    }//GEN-LAST:event_oraActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new SvegliaInterfaccia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton data;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton meno;
    private javax.swing.JButton ora;
    private javax.swing.JButton piu;
    private javax.swing.JButton stazione;
    private javax.swing.JButton sveglia;
    // End of variables declaration//GEN-END:variables

        
}

